#!/bin/bash

HELP="bl-install conky is a utility to copy the conky configuration files
installed by bunsen-conky into the user's home directory.
Files will be in $HOME/.config/conky

Usage:  bl-install-conky [-c|-copy] [-h|--help]

Options:
-c|-copy
    copy in the files
-h|--help
    display this message
"
SOURCE=/usr/share/bunsen/skel/conky
DEST=$HOME/.config

case $1 in
--help|-h|'')
    echo "$HELP"
    exit 0
    ;;
--copy|-c)
    [[ -d $SOURCE ]] || { echo "$SOURCE: no such directory" >&2;exit 1;}
    [[ -d $DEST ]] || { echo "$DEST: no such directory" >&2;exit 1;}
    echo 'copying files...'
    cp -r -i --backup --suffix="~$( date +%FT%T )~" "$SOURCE" "$DEST"
    echo 'done'
    ;;
*)
    echo "$1: unknown option.
$HELP"
    ;;
esac

echo 'Press any key to exit'
read -srn1

exit 0
