#!/bin/bash
## click to start, click to stop
## Original pkill line by: GrouchyGaijin - Ununtu Conky Thread
##    to start stop a specific conky
## This idea by: Stinkeye - Jan 2013 - Ununtu Conky Thread
## start/stop conky with pkill line
## With a tweak by: arclance
## Final tweak by: Sector11 - added wmctrl
## to start a connky on a specific desktop
## remove "sticky" from own_window_hints

## This incarnation created for Bunsen Labs
## Feb 2015

#if pgrep -f "conky -c /path_to/conky/name-of-the.conkyrc"
#then
#	pkill -xf "conky -c /path_to/conky/name-of-the.conkyrc"
#else
#	wmctrl -s 5 && conky -c "/path_to/conky/name-of-the.conkyrc"
#fi

if pgrep -f "conky -c $HOME/.config/conky/CB-TL.conkyrc"
then
	pkill -xf "conky -c $HOME/.config/conky/CB-TL.conkyrc"
else
	conky -c $HOME/.config/conky/CB-TL.conkyrc
fi